/*
 * Copyright (c) 2026 Enaium
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package cn.enaium.onnxruntime

import cnames.structs.*
import kotlinx.cinterop.*
import onnxruntime.*
import platform.posix.*

/**
 * Lazily resolves the [OrtApi] function-pointer table exported by the
 * bundled libonnxruntime shared library. Since 1.15 the C API is only
 * reachable through `OrtGetApiBase()->GetApi(ORT_API_VERSION)`; the
 * bindings generated by cinterop expose every table entry as a member of
 * the [OrtApi] struct.
 */
internal object Ort {

    val apiBase: CPointer<OrtApiBase> by lazy {
        OrtGetApiBase() ?: error("OrtGetApiBase() returned null - libonnxruntime failed to load")
    }

    val api: OrtApi by lazy {
        val api = apiBase.pointed.GetApi!!(ORT_API_VERSION.toUInt())
            ?: error("OrtApi version $ORT_API_VERSION is not supported by this libonnxruntime")
        api.pointed
    }

    /** Version string reported by the underlying library (e.g. "1.26.0"). */
    val versionString: String by lazy { apiBase.pointed.GetVersionString!!()?.toKString() ?: "unknown" }

    /** Default CPU allocator (a process-wide singleton; never freed). */
    val defaultAllocator: CPointer<OrtAllocator>? by lazy {
        memScoped {
            val out = alloc<CPointerVar<OrtAllocator>>()
            api.GetAllocatorWithDefaultOptions!!(out.ptr).check()
            out.value
        }
    }

    /** CPU memory info used for user-supplied tensor buffers (never freed). */
    val cpuMemoryInfo: CPointer<OrtMemoryInfo>? by lazy {
        memScoped {
            val out = alloc<CPointerVar<OrtMemoryInfo>>()
            api.CreateCpuMemoryInfo!!(
                OrtArenaAllocator,
                OrtMemTypeDefault,
                out.ptr,
            ).check()
            out.value
        }
    }
}

internal fun LogLevel.toOrt(): OrtLoggingLevel = when (this) {
    LogLevel.VERBOSE -> OrtLoggingLevel.ORT_LOGGING_LEVEL_VERBOSE
    LogLevel.INFO -> OrtLoggingLevel.ORT_LOGGING_LEVEL_INFO
    LogLevel.WARNING -> OrtLoggingLevel.ORT_LOGGING_LEVEL_WARNING
    LogLevel.ERROR -> OrtLoggingLevel.ORT_LOGGING_LEVEL_ERROR
    LogLevel.FATAL -> OrtLoggingLevel.ORT_LOGGING_LEVEL_FATAL
}

internal fun GraphOptimizationLevel.toOrt(): UInt = when (this) {
    GraphOptimizationLevel.DISABLE_ALL -> ORT_DISABLE_ALL
    GraphOptimizationLevel.ENABLE_BASIC -> ORT_ENABLE_BASIC
    GraphOptimizationLevel.ENABLE_EXTENDED -> ORT_ENABLE_EXTENDED
    GraphOptimizationLevel.ENABLE_ALL -> ORT_ENABLE_ALL
}

/**
 * Checks an [OrtStatusPtr] returned by an API call. Returns normally when
 * the call succeeded (null status) and throws [OnnxRuntimeException] with
 * the native error code and message otherwise.
 */
internal fun OrtStatusPtr?.check() {
    if (this != null) {
        val code = Ort.api.GetErrorCode!!(this)
        val message = Ort.api.GetErrorMessage!!(this)?.toKString() ?: "unknown error"
        Ort.api.ReleaseStatus!!(this)
        throw OnnxRuntimeException(code.ordinal, message)
    }
}

internal class NativeEnv internal constructor(
    internal val ptr: CPointer<OrtEnv>?,
) : Env {

    private var closed = false

    override val version: String get() = Ort.versionString

    override fun close() {
        if (!closed) {
            closed = true
            if (ptr != null) Ort.api.ReleaseEnv!!(ptr)
        }
    }
}

internal class NativeSessionOptions internal constructor(
    internal val ptr: CPointer<OrtSessionOptions>?,
) : SessionOptions {

    private var closed = false

    override fun setIntraOpNumThreads(threads: Int) {
        Ort.api.SetIntraOpNumThreads!!(ptr, threads).check()
    }

    override fun setInterOpNumThreads(threads: Int) {
        Ort.api.SetInterOpNumThreads!!(ptr, threads).check()
    }

    override fun setGraphOptimizationLevel(level: GraphOptimizationLevel) {
        Ort.api.SetSessionGraphOptimizationLevel!!(ptr, level.toOrt()).check()
    }

    override fun setSessionLogLevel(level: LogLevel) {
        Ort.api.SetSessionLogSeverityLevel!!(ptr, level.toOrt().value.toInt()).check()
    }

    override fun addConfigEntry(key: String, value: String) = memScoped {
        Ort.api.AddSessionConfigEntry!!(
            ptr,
            key.cstr.getPointer(memScope),
            value.cstr.getPointer(memScope),
        ).check()
    }

    override fun close() {
        if (!closed) {
            closed = true
            if (ptr != null) Ort.api.ReleaseSessionOptions!!(ptr)
        }
    }
}

internal class NativeRunOptions internal constructor(
    internal val ptr: CPointer<OrtRunOptions>?,
) : RunOptions {

    private var closed = false

    override fun setTerminate() {
        Ort.api.RunOptionsSetTerminate!!(ptr).check()
    }

    override fun unsetTerminate() {
        Ort.api.RunOptionsUnsetTerminate!!(ptr).check()
    }

    override fun close() {
        if (!closed) {
            closed = true
            if (ptr != null) Ort.api.ReleaseRunOptions!!(ptr)
        }
    }
}

internal class NativeSession internal constructor(
    private val ptr: CPointer<OrtSession>?,
) : Session {

    private var closed = false

    override val inputNames: List<String> by lazy { sessionNames(::inputCount, ::inputName) }
    override val outputNames: List<String> by lazy { sessionNames(::outputCount, ::outputName) }

    private fun inputCount(): ULong = memScoped {
        val out = alloc<ULongVar>()
        Ort.api.SessionGetInputCount!!(ptr, out.ptr).check()
        out.value
    }

    private fun outputCount(): ULong = memScoped {
        val out = alloc<ULongVar>()
        Ort.api.SessionGetOutputCount!!(ptr, out.ptr).check()
        out.value
    }

    private fun inputName(index: ULong): String = memScoped {
        val out = alloc<CPointerVar<ByteVar>>()
        Ort.api.SessionGetInputName!!(ptr, index, Ort.defaultAllocator, out.ptr).check()
        val name = out.value!!.toKString()
        Ort.defaultAllocator?.let { it.pointed.Free!!(it, out.value) }
        name
    }

    private fun outputName(index: ULong): String = memScoped {
        val out = alloc<CPointerVar<ByteVar>>()
        Ort.api.SessionGetOutputName!!(ptr, index, Ort.defaultAllocator, out.ptr).check()
        val name = out.value!!.toKString()
        Ort.defaultAllocator?.let { it.pointed.Free!!(it, out.value) }
        name
    }

    private inline fun sessionNames(
        count: () -> ULong,
        nameOf: (ULong) -> String,
    ): List<String> {
        val n = count()
        return List(n.toInt()) { i -> nameOf(i.toULong()) }
    }

    override fun run(
        inputs: Map<String, Tensor>,
        outputs: Set<String>,
        runOptions: RunOptions?,
    ): Map<String, Tensor> = memScoped {
        require(inputs.isNotEmpty()) { "At least one input is required" }

        val inputNameList = inputs.keys.toList()
        val ortInputNames = allocArray<CPointerVar<ByteVar>>(inputNameList.size)
        for (i in inputNameList.indices) ortInputNames[i] = inputNameList[i].cstr.getPointer(memScope)

        val ortInputValues = allocArray<CPointerVar<OrtValue>>(inputNameList.size)
        val inputValues = mutableListOf<CPointer<OrtValue>?>()
        try {
            for (i in inputNameList.indices) {
                val value = inputs.getValue(inputNameList[i]).toOrtValue(this)
                ortInputValues[i] = value
                inputValues += value
            }

            val outputNameList = outputs.toList()
            val ortOutputNames = allocArray<CPointerVar<ByteVar>>(outputNameList.size)
            for (i in outputNameList.indices) ortOutputNames[i] = outputNameList[i].cstr.getPointer(memScope)
            val ortOutputValues = allocArray<CPointerVar<OrtValue>>(outputNameList.size)

            Ort.api.Run!!(
                ptr,
                (runOptions as? NativeRunOptions)?.ptr,
                ortInputNames,
                ortInputValues,
                inputNameList.size.toULong(),
                ortOutputNames,
                outputNameList.size.toULong(),
                ortOutputValues,
            ).check()

            val result = LinkedHashMap<String, Tensor>(outputNameList.size)
            try {
                for (i in outputNameList.indices) {
                    val outPtr = ortOutputValues[i]
                        ?: throw OnnxRuntimeException(-1, "Session returned null output '${outputNameList[i]}'")
                    result[outputNameList[i]] = outPtr.toTensor()
                }
            } finally {
                for (i in outputNameList.indices) {
                    ortOutputValues[i]?.let { Ort.api.ReleaseValue!!(it) }
                }
            }
            result
        } finally {
            inputValues.forEach { if (it != null) Ort.api.ReleaseValue!!(it) }
        }
    }

    override fun close() {
        if (!closed) {
            closed = true
            if (ptr != null) Ort.api.ReleaseSession!!(ptr)
        }
    }
}

internal fun readFileBytes(path: String): ByteArray {
    val file = fopen(path, "rb") ?: throw OnnxRuntimeException(-1, "Failed to open model file: $path")
    try {
        fseek(file, 0, SEEK_END)
        val size = ftell(file)
        fseek(file, 0, SEEK_SET)
        if (size <= 0) return ByteArray(0)
        val buffer = ByteArray(size.toInt())
        val read = buffer.usePinned { pinned ->
            fread(pinned.addressOf(0), 1u, size.toULong(), file)
        }
        if (read != size.toULong()) {
            throw OnnxRuntimeException(-1, "Failed to read model file: $path")
        }
        return buffer
    } finally {
        fclose(file)
    }
}

actual fun createEnv(logLevel: LogLevel, logId: String): Env = memScoped {
    val out = alloc<CPointerVar<OrtEnv>>()
    Ort.api.CreateEnv!!(logLevel.toOrt(), logId.cstr.getPointer(memScope), out.ptr).check()
    NativeEnv(out.value)
}

actual fun createSessionOptions(): SessionOptions = memScoped {
    val out = alloc<CPointerVar<OrtSessionOptions>>()
    Ort.api.CreateSessionOptions!!(out.ptr).check()
    NativeSessionOptions(out.value)
}

actual fun createRunOptions(): RunOptions = memScoped {
    val out = alloc<CPointerVar<OrtRunOptions>>()
    Ort.api.CreateRunOptions!!(out.ptr).check()
    NativeRunOptions(out.value)
}

actual fun createSession(env: Env, modelPath: String, options: SessionOptions?): Session =
    createSession(env, readFileBytes(modelPath), options)

actual fun createSession(env: Env, model: ByteArray, options: SessionOptions?): Session {
    val nativeEnv = env as NativeEnv
    return model.usePinned { pinned ->
        memScoped {
            val out = alloc<CPointerVar<OrtSession>>()
            Ort.api.CreateSessionFromArray!!(
                nativeEnv.ptr,
                pinned.addressOf(0),
                model.size.toULong(),
                (options as? NativeSessionOptions)?.ptr,
                out.ptr,
            ).check()
            NativeSession(out.value)
        }
    }
}
